version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB= postgres
      - POSTGRES_USER= postgres
      - POSTGRES_PASSWORD= postgres
  backend:
    container_name: backend
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/backend
    ports:
      - "8000:8000"
    depends_on:
      - db
  frontend:
    container_name: frontend
    build: ./frontend/commit-viewer
    command: bash -c "npm rebuild node-sass && yarn start"
    volumes:
      - /frontend/commit-viewer/node_modules
      - ./frontend/commit-viewer:/frontend
    ports:
      - 3000:3000
    stdin_open: true
