# Generated by Django 3.2.6 on 2021-08-06 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubCommitParent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('html_url', models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name='commit',
            name='message',
            field=models.CharField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='githubcommit',
            name='parents',
            field=models.ManyToManyField(related_name='children', to='back.GitHubCommitParent'),
        ),
    ]
