# Generated by Django 3.2.6 on 2021-08-06 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0002_auto_20210806_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='email',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='githubcommit',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_commits', to='back.user'),
        ),
        migrations.AlterField(
            model_name='githubcommit',
            name='committer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committer_commits', to='back.user'),
        ),
    ]
