# Generated by Django 3.2.6 on 2021-08-07 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Commit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=3000)),
                ('treeUrl', models.URLField()),
                ('url', models.URLField()),
                ('comment_count', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commits', to='back.author')),
            ],
        ),
        migrations.CreateModel(
            name='GitHubCommitParent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('html_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gitId', models.CharField(max_length=30)),
                ('avatarUrl', models.URLField()),
                ('apiUrl', models.URLField()),
                ('htmlUrl', models.URLField()),
                ('reposUrl', models.URLField()),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GitHubCommit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('htmlUrl', models.URLField()),
                ('commentsUrl', models.URLField()),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author_commits', to='back.user')),
                ('commit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='back.commit')),
                ('committer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='committer_commits', to='back.user')),
                ('parents', models.ManyToManyField(related_name='children', to='back.GitHubCommitParent')),
            ],
        ),
    ]
