# Generated by Django 3.2.6 on 2021-08-07 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='date',
            field=models.CharField(max_length=100),
        ),
    ]
